### PR TITLE
Fix Local User Persistence / Fix MindfulnessTip/SessionRating PopupService Issues / Add TryCatches to API calls

### LINKED ISSUE #85: Sprint 4 Bug Fixes
## Problem
Fixing up loose ends from Sprint 4

## Definition of Done
- User is added to local database on sign in if not already there
- App no longer crashes when popup service attempts to access disposed popup
- Make app more reliable
- Make app give helpful logs

## Subtasks
- [x] Add user to local database on sign in if not already there
- [x] Prevent users from dismissing popups via clicking outside of the box
- [x] Add try/catches to API calls
- [x] Add logs to pages, log when API calls fail

### PR DESCRIPTION
**Pull request by iggy808**
Fixes #85 

## Problem
- User was not being added to local database if nonexistent on startup
- UserPets not being added to the local database optimally
- App would crash if API calls failed
- Add logging for when API calls fail
- Popups were being disposed outside of the PopupService stack, resulting in app crash when popup attempted to be accessed

### Definition of Done
- User is added to local database on sign in if not already there
- App no longer crashes when popup service attempts to access disposed popup
- Make app more reliable
- Make app give helpful logs

## Solution
- User is added to local database on sign in if not already there
- User pets added to local database via user instance (no longer direct insert into UserPets table)
- Added try/catches around API calls
- Added logger to login page and shop popups for when API calls fail
- Prevented users from dismissing popups via clicking out of them

## How was this tested?
Manually

### CODE REVIEW

File: src/FocusAPI/Methods/User/AddUserFurniture.cs [hunk 1]
```diff
@@ -19,11 +19,10 @@ public async Task<Unit> Handle(AddUserFurnitureCommand command, CancellationToke
             FocusAPI.Models.User user = _context.Users.First(u => u.Id == command.UserId);
```
Comment (ChrispyPeaches) [inline src/FocusAPI/Methods/User/AddUserFurniture.cs:19]: This line is an example of a Db call that could have async-await and a try catch block added to it. You could have a try-catch around these two calls and another around the save changes async call at the bottom. it's up to you, but it would help to have at least a try-catch that would catch and allow you to add explanations to any unexpected errors from the DB calls.

File: src/FocusApp.Client/Views/Shop/ShopItemPopupInterface.cs [hunk 2]
```diff
@@ -242,21 +266,31 @@ private async void PurchaseItem(object sender, EventArgs e)
...
+                        {
+                            UserId = _authenticationService.CurrentUser.Id,
+                            SoundId = _currentItem.Id,
+                            UpdatedBalance = _authenticationService.CurrentUser.Balance,
+                        });
+                    }
+                    catch (Exception ex)
+                    {
+                        _logger.Log(LogLevel.Error, "Error adding UserSound to server database. Exception: " + ex.Message);
+                    }
```
Comment (ChrispyPeaches) [inline src/FocusApp.Client/Views/Shop/ShopItemPopupInterface.cs:293]: Awesome job on the try-catch blocks here (in this file) 👏

File: src/FocusApp.Client/Views/Shop/ShopItemPopupInterface.cs [hunk 3]
```diff
@@ -208,20 +222,30 @@ private async void PurchaseItem(object sender, EventArgs e)
                     }
 
                     // Add the user's new furniture to the local database
-                    _localContext.UserFurniture.Add(new UserFurniture
+                    user = _localContext.Users.First(u => u.Id == _authenticationService.CurrentUser.Id);
```
Comment (ChrispyPeaches) [inline src/FocusApp.Client/Views/Shop/ShopItemPopupInterface.cs:225]: Here's another example of a Db call that would benefit from being inside of a try-catch block and from using async-await syntax

**Review by ChrispyPeaches — CHANGES_REQUESTED** [review]
Thanks and great changes, these will help us out a ton!

I do have some requested changes:
- Could we add async await syntax to the API's DB calls?
- Could we have try-catch blocks added to the API's controller feature calls and DB calls?
    - For clarity, this is referencing the MediatR method in the User folder and the controller calling those.
    - I know ur familiar with this stuff, but just to make things easier, here's some links to examples
    - [Example of try catch block around feature linked here](https://github.com/ChrispyPeaches/FocusFriends/blob/4daae811bb0da3fdba120e3a161b337c457b4573/src/FocusAPI/Controllers/SyncController.cs#L37-L47)
    - [Example of async-await syntax and try-catch block around db call here](https://github.com/ChrispyPeaches/FocusFriends/blob/4daae811bb0da3fdba120e3a161b337c457b4573/src/FocusAPI/Methods/Sync/SyncMindfulnessTips.cs#L57-L67)
    - This helps ensure threads aren't locked up when waiting on DB to answer and helps track down errors

I'd also like to point out that you did an awesome job on the added try-catch blocks in the FocusApp!

File: src/FocusAPI/Methods/User/AddUserFurniture.cs (hunk 1 above)
Comment (iggy808) [reply src/FocusAPI/Methods/User/AddUserFurniture.cs:19]: Don't think you can await-async "First" calls with LINQ - are these the line you are referring to?  Working on the Try/Catches now, but not sure which lines you're targeting with the async-await!

Comment (ChrispyPeaches) [reply src/FocusAPI/Methods/User/AddUserFurniture.cs:19]: Yeah those were the lines I was referring to. Similarly to how you can't await ToList(), but you can await ToListAsync(), you can await FirstAsync() or FirstOrDefaultAsync(). [Example linked here](https://github.com/ChrispyPeaches/FocusFriends/blob/4daae811bb0da3fdba120e3a161b337c457b4573/src/FocusApp.Client/Methods/MindfulnessTip/GetMindfulnessTipByRatingLevel.cs#L73-L76)

**Review by ChrispyPeaches — APPROVED** [review]
Looks amazing! 
Thanks for cleaning all of these bugs up quickly and making the requested changes so quickly!

**Review by wesleypayton — APPROVED** [review]
Perfecto 🤏
